[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 3000

# Redirecciones específicas para manejar rutas de GitHub Pages
[[redirects]]
  from = "/contadom"
  to = "/"
  status = 301

[[redirects]]
  from = "/contadom/*"
  to = "/:splat"
  status = 301

# Redirección para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configura las variables de entorno directamente en el panel de Netlify 